export const NAMES_FIRST = [
    'Adric',
    'Aldo',
    'Amosen',
    'Andrel',
    'Arden',
    'Arlyn',
    'Arquo',
    'Arvus',
    'Ashlyn',
    'Branon', 'Brace', 'Brance',
    'Brena', 'Bricks', 'Candra',
    'Carissa', 'Carro', 'Casslyn',
    'Cavelle', 'Clave', 'Corille',
    'Cross', 'Crowl', 'Cyrene',
    'Daphnia', 'Drav', 'Edlun',
    'Emeline', 'Grine', 'Helles',
    'Hix', 'Holtz', 'Kamelin',
    'Kelyr', 'Kobb', 'Kristov',
    'Laudius', 'Lauria', 'Lenia',
    'Lizete', 'Lorette', 'Lucella',
    'Lynthia', 'Mara', 'Milos',
    'Morlan', 'Myre', 'Narcus',
    'Naria', 'Noggs', 'Odrienne',
    'Orlan', 'Phin', 'Polonia',
    'Quess', 'Remira', 'Ring',
    'Roethe', 'Sesereth', 'Sethla',
    'Skannon', 'Stavrul', 'Stev',
    'Syra', 'Talitha', 'Tesslyn',
    'Thena', 'Timoth', 'Tocker',
    'Una', 'Vaurin', 'Veleris',
    'Veretta', 'Vestine', 'Vey',
    'Volette', 'Vond', 'Weaver',
    'Wester', 'Zamira',
    'Whitney',
    'Erika',
    'Lance',
    'Ripley',
    'Coheed',
    'Cambria',
    'Vaxis',
    'Newo',
    'Orthis',
    'Adrian',
    'Rem',
    'Aranaia',
    'Lem',
    'Breem',
    'Vimes',
    'Skint',
    'Saffron',
    'Beryl',
    'Imogen',
    'Jar',
    'Silva',
    'Horst',
    'Haxar',
    'Striga',
    'Edelhart',
    'Gavlan',
    'Thorn',
    'Liv',
    'Raphiela',
    'Kreet',
    'Leander',
    'Mercutio',
    'Satis',
    'Elizabeth',
    'Grim',
    'Eldread',
    'Odham',
    'Willow',
    'Seasong',
    'Avalanche',
    'Judas',
    'Cassius',
    'Albert',
    'Rani',
    'Agrippa',
    'Streben',
    'Imnel',
    'Doc',
    'Norman',
    'Aliaster',
    'Adalina',
    'Sabrina',
    'Sperro',
    'Eugene',
    'Vincent',
    'Viktor',
    'Rhonda',
    'Jenny',
    'Regin',
    'Dearni',
    'Kotlin',
    'Gram',
    'Din',
    'Tyrant Slayer',
    'Obadiah',
    'El',
    'Moil',
    'Theo',
    'Marrianne',
    'Rom',
    'Louis Rex',
    'Varius',
    'Altum',
    'Ephie',
    'Anya',
    'Ramal',
    'Cirrus',
    'Foam',
    'Shale',
    'Bismark',
    'Prismarine',
    'Crush',
    'Abyss',
    'Jacklyn',
    'Zant',
    'Camilla',
    'Vilgot',
    'Ellis',
    'Falak',
    'Marshall',
    'Faragar',
    'Pelle',
    'Gaur',
    'Dutch',
    'Jaspar',
    'Sined',
    'Karsus',
    'Albedo',
    'Astarot',
    'Zola',
    'Kaiman',
    'Noi',
    'Shin',
    'Sybil',
    'Errol',
    'Iris',
    'Pyrite',
    'Rorick',
    'Hitomi',
    'Gianna',
    'Vigil',
    'Purity',
    'Pitch',
    'Bagherra',
    'Cersei',
    'Quinn',
    'Ein',
    'Luna',
    'Lemillion',
    'Matrakin',
    'Zandakar',
    'Leviathan',
    'Mary',
    'Amon',
    'Abraxas',
    'Adrammelech',
    'Akuma',
    'Baal',
    'Barbatos',
    'Asmodeus',
    'Astaroth',
    'Belial',
    'Clauneck',
    'Eligos',
    'Flauros',
    'Focalor',
    'Foras',
    'Forneus',
    'Furcas',
    'Furfur',
    'Gaap',
    'Gamigin',
    'Gemory',
    'Haagenti',
    'Halphas',
    'Ipos',
    'Kimaris',
    'Leraje',
    'Malphas',
    'Marbas',
    'Marchosias',
    'Morax',
    'Naberius',
    'Orias',
    'Orobas',
    'Ose',
    'Paimon',
    'Phenex',
    'Raum',
    'Ronove',
    'Sabnock',
    'Sallos',
    'Seere',
    'Shax',
    'Sitri',
    'Stolas',
    'Surgat',
    'Valac',
    'Valefar',
    'Vassago',
    'Vine',
    'Zagan',
    'Zepar',
    'Ziminiar',
];

export const NAMES_LAST = [
    'Ankhayat', 'Arran',
    'Athanoch', 'Basran',
    'Boden', 'Booker', 'Bowman',
    'Breakiron', 'Brogan',
    'Clelland', 'Clermont',
    'Coleburn', 'Comber',
    'Daava', 'Dalmore',
    'Danfield', 'Dunvil', 'Farros',
    'Grine', 'Haig', 'Helker',
    'Helles', 'Hellyers', 'Jayan',
    'Jeduin', 'Kardera', 'Karstas',
    'Keel', 'Kessarin', 'Kinclaith',
    'Lomond', 'Maroden',
    'Michter', 'Morriston',
    'Penderyn', 'Prichard',
    'Rowan', 'Sevoy', 'Skelkallan',
    'Skora', 'Slane', 'Strangford',
    'Strathmill', 'Templeton',
    'Tyrconnell', 'Vale', 'Walund',
    'Welker', 'Fynfier',
];

export const PRONOUNS_FIRST = [
    'He', 'She', 'They'
];

export const PRONOUNS_LAST = [
    'Him', 'Her', 'Them'
];

export const ALIAS = [
    'Bell', 'Birch', 'Bricks', 'Bug',
    'Chime', 'Coil', 'Cricket',
    'Cross', 'Crow', 'Echo', 'Flint',
    'Frog', 'Frost', 'Grip', 'Gunner',
    'Hammer', 'Hook', 'Junker',
    'Mist', 'Moon', 'Nail', 'Needle',
    'Ogre', 'Pool', 'Ring', 'Ruby',
    'Silver', 'Skinner', 'Song',
    'Spur', 'Tackle', 'Thistle',
    'Thorn', 'Tick-Tock',
    'Twelves', 'Vixen', 'Whip',
    'Wicker'
];

export const LOOK = [
    'man', 'woman', 'ambiguous', 'concealed'
];

export const HERITAGE = [
    'Akoros',
    'Skovland',
    'Iruvia',
    'The Dagger Island',
    'Severos',
    'Tycheros',
];

export const FOREIGN = [
    'Skovland',
    'Iruvian',
    'Dagger Islander',
    'Severosi',
    'Tycherosi',
];

export const SKIN_TONE = [
    'palid',
    'fair',
    'amber',
    'copper',
    'umber',
    'dark',
];

export const BUILD = [
    'gaunt',
    'stout',
    'chubby',
    'muscular',
    'curvacious',
    'broad-shouldered',
    'thick-thighed',
    'lithe',
];

export const DISTINGUISH = [
    'the golden filigree racing across their body',
    'the many candles that are stuck to their shoulders',
    'that they are covered in old scars',
    'their missing eye',
    'their missing hand',
    'their missing leg',
    'their missing arm',
    'their prosthetic eye',
    'their prosthetic hand',
    'their prosthetic leg',
    'their prosthetic arm',
    'their vitiligo',
    'their colorful tattoos',
    'their monochromatic tattoos',
    'that they are coated in freckles',
    'their hetrochroma',
    'their dyed hair',
    'their obvious piercings',
    'their one gold tooth',
    'their distinguished mole',
    'their split tounge',
    'that they are bedecked in jewelry',
    'their immaculately painted nails',
    'their intricate makeup',
    'their beautiful scarification',
    'their prominent nose',
    'their gap-toothed smile',
    'their button nose',
    'their slitted eyebrows',
    'their intricate hair-do',
    'their ink-stained fingers',
];

export const TYCHEROSI = [
    'black shark eyes',
    'onyx scales',
    'iridescent scales',
    'crytalline scales',
    'metallic scales',
    'razor-sharp claws',
    'bony protrusions like armor',
    'cluster of eyes',
    'long, lashing tail',
    'leathery bat-like wings',
    'rows of spines',
    'thick fur',
    'hair that floats as if underwater',
    'oily black crow feathers',
    'multiple arms',
    'glowing, cat-like eyes',
    'burning, goat-like eyes',
    'rows of sharp teeth',
    'cat-like ears',
    'dog-like ears',
];

export const TRAITS = [
    'charming',
    'cold',
    'cavalier',
    'brash',
    'suspicious',
    'obsessive',
    'shrewd',
    'quiet',
    'moody',
    'fierce',
    'careless',
    'secretive',
    'ruthless',
    'calculating',
    'defiant',
    'gracious',
    'insightful',
    'dishonest',
    'patient',
    'vicious',
    'sophisticated',
    'paranoid',
    'enthusiastic',
    'elitist',
    'savage',
    'cooperative',
    'arrogant',
    'confident',
    'vain',
    'daring',
    'volatile',
    'candid',
    'subtle',
    'melancholy',
    'enigmatic',
    'calm',
];

export const STYLES = [
    'tricorn hat fitted loosely',
    'Long Coat wrapped around their body',
    'Hood & Veil that conceals their face',
    'Short Cloak that flaps fitfully in the breeze',
    'Knit Cap pulled tightly over their ears',
    'Slim Jacket riddled with patches',
    'Hooded Coat buttoned up tight',
    'pair of Tall Boots laced with precision',
    'pair of Work Boots worn with use',
    'set of Mask & Robes that smells faintly of frankincense',
    'Suit & Vest worn smartly',
    'Collared Shirt with the sleeves rolled up',
    'set of Suspenders, with one of them hanging off the shoulder',
    'Rough Tunic tucked into their pants',
    'Skirt & Blouse that flutters gently',
    'Wide Belt with a distinct patina',
    'Fitted Dress that shows off their body',
    'Heavy Cloak that hides both body and intent',
    'Thick Greatcoat britsling with the promise of violence',
    'pair of Soft Boots with the laces loosely tied',
    'Loose Silks of multiple colors',
    'pair of Sharp Trousers ironed to a razor\'s edge',
    'Waxed Coat beaded with moisture - or blood',
    'Long Scarf that dances like a flag',
    'Leathers marked with cuts',
    'Eelskin Bodysuit that glistens in the dim lamplight',
    'Hide & Furs of some unknown and terrible beast',
    'Uniform that sets your teeth on edge',
    'pair of Fitted Leggings showing off their graceful finesse',
    'Apron marked with many and multi-colored stains',
    'set of Heavy Gloves marked with a history of violence',
    'Face Mask that hides their mouth and expression',
    'Tool Belt fitted with well-used and well-loved implements',
    'set of Crutches featuring beautiful ivory and gold inlay',
    'Cane topped with the head of some snarling creature; Probably a sword',
    'Wheelchair of delicate filigree, fitted with an electroplasmic battery',
];

export const GOALS = [
    'for more coin than you can possibly fathom',
    'for the power to crush their enemies',
    'for authority to be wielded like a hammer',
    'for their achievements to be recognized',
    'for a modicum of control in all this insanity',
    'for deep and specialized knowledge',
    'to know the warmth of another',
    'to eat decadent foods',
    'to scramble their brains with drugs',
    'for slow and brutal vengeance',
    'to be free from their debts',
    'to escape from Doskvol',
    'for small comforts and humble happiness',
    'to have their name to be spoken alongside the greats',
    'for their name to be whispered in fear',
    'for the respect of their peers',
    'to find someone to love and to be loved',
    'to fix the inequity of Doskvol',
    'to rip the order and tedium of this place down',
    'for complete and total chaos',
    'to right the wrongs of this world',
    'to find a team'
];


export const METHOD = [
    'sudden and brutal violence',
    'threats of violence',
    'negociating mutually beneficial deals',
    'studying long and esoteric texts',
    'manipulating others',
    'long and complex strategy',
    'bloodless theivery',
    'rituals beseeching a dark and strange god',
    'communing with ghosts',
    'consorting with devils',
    'a little side hustle',
    'long and grueling hours at their job',
    'abusing the justice system',
    'getting involved in local politics',
    'careful and well-planned sabotage',
    'quiet and unknown methods in the deepest dark',
    'crafting strange alchemical concoctions',
    'obsessively studying their opponents and blackmailing them',
    'smooth and selfless teamwork',
    'precise espionage',
    'completely nonsensical chaos'
];

export const PROFESSION = [
    'Baker', 'Barber', 'Blacksmith', 'Brewer', 'Butcher', 'Carpenter',
    'Cartwright', 'Chandler', 'Clerk', 'Cobbler', 'Cooper', 'Cultivator',
    'Driver', 'Dyer', 'Embroiderer', 'Fishmonger', 'Gondolier', 'Guard',
    'Leatherworker', 'Mason', 'Merchant', 'Roofer', 'Ropemaker', 'Rug Maker',
    'Servant', 'Shipwright', 'Criminal', 'Tailor', 'Tanner', 'Tinkerer',
    'Vendor', 'Weaver', 'Woodworker', 'Eel Farmer', 'Messenger', 'Sailor',

    'Advocate', 'Architect', 'Artist', 'Author', 'Bailiff', 'Apiarist',
    'Banker', 'Bounty Hunter', 'Clockmaker', 'Courtesan', 'Furrier', 'Glass Blower',
    'Diplomat', 'Jailer', 'Jeweler', 'Leech', 'Locksmith', 'Magistrate',
    'Musician', 'Physicker', 'Plumber', 'Printer', 'Scholar', 'Scribe',
    'Sparkwright', 'Tax Collector', 'Treasurer', 'Whisper', 'Composer', 'Steward',
    'Captain', 'Spirit Warden', 'Journalist', 'Explorer', 'Rail Jack', 'Soldier',
];

export const INTERESTS = [
    'aged whiskey from from the Dagger Isles',
    'honeyed wine from Skovland',
    'classic beers right from Akoros',
    'expensive foods from Whitecrown',
    'street food from the Nightmarket',
    'trying on fine clothes from Dunridge & Sons',
    'purusing jewels mined from the Deathlands',
    'touching, smelling, and wearing the furs of exotic beasts',
    'the theatre, the opera, and musicals',
    'painting fantastical landscapes in oils',
    'rendering the brutal truth of the world on a canvas',
    'obsessively creating sculptures of their nightmares out of junk',
    'carefully sculpting people to show them the beauty hidden within',
    'studying the history of the Shattered Isles',
    'delving into the legends of Akoros',
    'plumbing the depths of pre-cataclysm legends',
    'meandering around town to appreciate the architecture',
    'learning about the architecture of the other islands',
    'flower arrangement and tea ceremonies',
    'writing love poems',
    'scribbling down slam poetry',
    'wittling away at an over-long novel',
    'feeling alive while pit-fighting',
    'honing their skills in one-on-one duels',
    'collecting arbitrary items for their altar to a forgotton god',
    'purifying their spirit according to the tenants of the Church of Ecstasy',
    'buying blackmarket ghost bottles for the Path of Echoes',
    'passing out mushroom loafs and preaching about the Weeping Lady',
    'collecting antiques and curios from Doskvols past',
    'riding ghost-eating horses',
    'tinking with electropasmic gadgets',
    'collecting rare weapons',
    'playing with a local band',
    'dancing with a crowd at a dancehall',
    'honoring and sharing their past by performing traditional dance',
    'singing enthusiastically at the local pub',
    'being part of a choir at their local church',
    'fishing out in the canals',
    'practicing their marksmanship',
    'cooking for their neighbors',
    'hunting down ingredients to make traditional meals',
    'tending to their closet mushroom farm',
    'gossiping while tending to the community mushroom tunnels',
    'the pure adrenaline hit from gambling a weeks-worth of work',
    'yelling at the top of their lungs at the hound races',
    'losing or winning it all at the rat-fighting pits',
    'studying philosophy at Doskvol Academy',
    'getting completly trashed on Black Lotus',
    'flirting shamelessly with anyone looks their way',
    'participating in neighborhood potlucks',
    'dressing to the nines and attendning fancy soirees',
    'exploring abandoned buildings and canals around Doskvol',
    'sneaking out past the lighting barriers to explore the Deathlands',
    'fostering stray cats',
    'teaching crows how to commit minor crimes',
    'working with their hands to make leather clothes',
    'the rattle of a hammer striking steel while blacksmithing',
    'the quiet meditation that comes from wittling petrified wood',
    'going out into the canals on their makeshift raft',
    'staying abreast of local politics',
    'collecting and studying arcane texts',
    'hunting down arcane rituals',
    'summoning and speaking with the unquiet dead through careful spectrology',
    'crafting potions and poultices in their amatuer lab',
];